# Generated by Django 3.0.6 on 2020-12-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('product', models.IntegerField(verbose_name='product')),
                ('bidder', models.IntegerField(verbose_name='bidder')),
                ('price', models.IntegerField(verbose_name='price')),
                ('uploadTime', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AuctionInformation',
                'verbose_name_plural': 'AuctionInformations',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('buyer', models.IntegerField(verbose_name='buyer')),
                ('product', models.IntegerField(verbose_name='product')),
                ('uploadTime', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='FeedBackInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('usertype', models.CharField(max_length=10, verbose_name='usertype')),
                ('inner', models.CharField(max_length=200, verbose_name='inner')),
            ],
            options={
                'verbose_name': 'FeedBackInformation',
                'verbose_name_plural': 'FeedBackInformations',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('productName', models.CharField(max_length=20, verbose_name='productName')),
                ('pictureName', models.CharField(max_length=50, null=True, verbose_name='pictureName')),
                ('seller', models.IntegerField(verbose_name='seller')),
                ('buyer', models.IntegerField(verbose_name='buyer')),
                ('price', models.IntegerField(verbose_name='price')),
                ('sellType', models.CharField(max_length=10, verbose_name='sellType')),
                ('sellerNumber', models.CharField(max_length=20, verbose_name='sellerNumber')),
                ('sellerName', models.CharField(max_length=20, verbose_name='sellerName')),
                ('tradePlace', models.CharField(max_length=50, verbose_name='tradePlace')),
                ('uploadTime', models.DateField(auto_now_add=True)),
                ('endTime', models.DateField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('username', models.CharField(max_length=30, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('usertype', models.CharField(max_length=10, verbose_name='usertype')),
            ],
            options={
                'verbose_name': 'user information',
                'verbose_name_plural': 'users',
            },
        ),
    ]
