# Generated by Django 3.0.6 on 2020-12-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea', '0004_auto_20201221_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buyer',
            field=models.IntegerField(default=-1, verbose_name='buyer'),
        ),
    ]
