# Generated by Django 3.0.6 on 2020-12-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flea', '0006_auto_20201221_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='endTime',
            field=models.DateTimeField(null=True),
        ),
    ]
